spring:
  config:
    import: "optional:file:.env"
  datasource:
    url: ""
    username: ADMIN
    password: 
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForLocalDevOnlyWithMinimumLengthOf32Bytes!}
  expiration: 3600000

server:
  port: 8080
